### ISSUE TITLE
f64 precision problem

### ISSUE THREAD

**Issue by whsqjss** [rekka/meval-rs#31]
```
(2.27 - 2) / 3 should be 0.09, but got 0.09000000000000000001
```
Is there a solution to this problem? 
Looking forward to your reply. Thanks
![err](https://github.com/rekka/meval-rs/assets/35548533/f47c6e5e-8777-47e7-b057-452b47f38661)

**Comment by rekka** [comment]
This is a limitation of how computers handle floating point numbers so there is not much that can be done about this if we want to use the fast hardware floating point operations. See for example Python documentation: [Floating Point Arithmetic: Issues and Limitations](https://docs.python.org/3/tutorial/floatingpoint.html)

You can try the same expression in Rust directly:

```rust
fn main() {
    let x = (2.27 - 2.) / 3.;
    println!("{x}");
    let x = 0.3 * 3.;
    println!("{x}");
}
```

This prints 

```
0.09000000000000001
0.8999999999999999
```

Hope this helps.
